import assert from "node:assert/strict";
import { chmod, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { CodexClient } from "../local/codex-client.ts";

test("Codex client can initialize an isolated signed-out profile", async () => {
  const codexHome = await mkdtemp(join(tmpdir(), "gpt-account-manager-test-"));
  const codexBin = join(codexHome, "fake-codex.mjs");
  await writeFile(codexBin, `#!/usr/bin/env node
import { createInterface } from "node:readline";
const lines = createInterface({ input: process.stdin });
lines.on("line", (line) => {
  const message = JSON.parse(line);
  if (!Object.hasOwn(message, "id")) return;
  const result = message.method === "account/read"
    ? { account: null, requiresOpenaiAuth: true }
    : {};
  process.stdout.write(JSON.stringify({ id: message.id, result }) + "\\n");
});
`, { mode: 0o755 });
  await chmod(codexBin, 0o755);
  const client = new CodexClient({ codexHome, codexBin });
  try {
    await client.start();
    const result = await client.request("account/read", { refreshToken: false });
    assert.equal(result.account, null);
    assert.equal(result.requiresOpenaiAuth, true);
  } finally {
    client.close();
    await rm(codexHome, { recursive: true, force: true });
  }
});

test("account UI provides authentication, real usage, switching and devices", async () => {
  const dashboard = await readFile(new URL("../app/dashboard.tsx", import.meta.url), "utf8");
  const server = await readFile(new URL("../local/server.ts", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");

  assert.match(dashboard, /type="password"/);
  assert.match(dashboard, /\/api\/accounts\/login/);
  assert.match(dashboard, /\/activate/);
  assert.match(dashboard, /选择设备/);
  assert.match(dashboard, /选择使用这个账号的电脑/);
  assert.match(dashboard, /全部设备切换/);
  assert.match(dashboard, /switchRequestInFlight/);
  assert.match(dashboard, /switchAccount/);
  assert.match(dashboard, /force: device\.activeAccountId === account\.id/);
  assert.match(dashboard, /修改设备名称/);
  assert.match(dashboard, /saveDeviceName/);
  assert.match(dashboard, /CURRENT_SWITCHER_VERSIONS = \{ mac: "1\.8\.0", windows: "1\.8\.0" \}/);
  assert.match(dashboard, /模型消耗占比/);
  assert.match(dashboard, /modelTotals/);
  assert.match(dashboard, /isSwitcherOutdated/);
  assert.match(dashboard, /切换器 v\{device\.agentVersion \|\| "未知"\}/);
  assert.doesNotMatch(dashboard, /device\.agentVersion !== "1\.5\.0"/);
  assert.match(dashboard, /\/api\/devices/);
  assert.match(dashboard, /可用重置/);
  assert.match(dashboard, /全部刷新/);
  assert.match(dashboard, /账号排序/);
  assert.match(dashboard, /剩余额度：少到多/);
  assert.match(dashboard, /useState<SortMode>\("remaining-asc"\)/);
  assert.ok(dashboard.indexOf('<option value="remaining-asc">') < dashboard.indexOf('<option value="remaining">'));
  assert.match(dashboard, /切换记录/);
  assert.match(dashboard, /connectedDeviceNames/);
  assert.match(dashboard, /设备正在使用/);
  assert.match(dashboard, /暂无设备使用/);
  assert.match(dashboard, /编辑账号备注/);
  assert.match(dashboard, /role="progressbar"/);
  assert.match(dashboard, /formatResetCountdown/);
  assert.match(dashboard, /windowDurationMins/);
  assert.match(dashboard, /rateLimitWindows/);
  assert.match(dashboard, /总额度/);
  assert.match(dashboard, /5 小时额度/);
  assert.match(dashboard, /estimatedRemainingTokens/);
  assert.match(dashboard, /估算剩余/);
  assert.match(dashboard, /five-hour-progress/);
  assert.match(dashboard, /还剩\$\{days\}天\$\{hours\}小时\$\{minutes\}分刷新/);
  assert.doesNotMatch(dashboard, /重置：\{formatReset/);
  assert.match(dashboard, /metric-refresh/);
  assert.match(dashboard, /每日 Token 用量/);
  assert.match(dashboard, /dailyUsageBuckets/);
  assert.match(dashboard, /最近 14 天/);
  assert.match(dashboard, /accountPlusEquivalent/);
  assert.match(dashboard, /本周期折算/);
  assert.match(dashboard, /个 Plus/);
  assert.match(dashboard, /plusRemainingTotal/);
  assert.match(dashboard, /plusCapacityTotal/);
  assert.match(dashboard, /plusRemainingPercent/);
  assert.match(dashboard, /余额 \{formatPlusValue\(plusRemainingTotal\)\} Plus/);
  assert.match(dashboard, /总量 \{formatPlusValue\(plusCapacityTotal\)\} Plus/);
  assert.match(dashboard, /className="plus-battery" role="progressbar"/);
  assert.match(dashboard, /todayPlus/);
  assert.match(dashboard, /last7Plus/);
  assert.match(dashboard, /peakPlus/);
  assert.match(dashboard, /daily-tooltip-plus/);
  assert.match(dashboard, /dailyUsage\.peak \* 82/);
  assert.match(dashboard, /className="daily-tooltip"/);
  assert.match(dashboard, /aria-label="页面目录"/);
  assert.match(dashboard, /href="#accounts"/);
  assert.match(dashboard, /href="#usage"/);
  assert.match(dashboard, /href="#devices"/);
  assert.ok(dashboard.indexOf('id="usage"') < dashboard.indexOf('id="devices"'));
  assert.match(dashboard, /Token 消耗趋势/);
  assert.match(dashboard, /设备每分钟上报/);
  assert.match(dashboard, /usageTrend/);
  assert.match(dashboard, /\/api\/usage-timeline/);
  assert.doesNotMatch(dashboard, /relayTrend|relayModels|\/api\/relay-stats/);
  assert.match(dashboard, /visibleHistoryPage = Math\.min\(historyPage, historyPageCount\)/);
  assert.match(dashboard, /history\.slice\(\(visibleHistoryPage - 1\) \* 5, visibleHistoryPage \* 5\)/);
  assert.match(dashboard, /aria-label="切换记录分页"/);
  assert.doesNotMatch(dashboard, /Tibo|tiboMonitor|重置预测/);
  assert.doesNotMatch(dashboard, /\/launch|打开 Codex/);
  assert.match(server, /chatgptDeviceCode/);
  assert.match(server, /account\/rateLimits\/read/);
  assert.match(server, /account\/usage\/read/);
  assert.match(server, /availableModels\.includes\("gpt-6-astra"\)/);
  assert.match(server, /USAGE_REFRESH_INTERVAL_MS \|\| 300_000/);
  assert.match(server, /\/api\/device\/commands\/next/);
  assert.match(server, /\/api\/switch-history/);
  assert.match(server, /\/api\/usage-timeline/);
  assert.match(server, /mergeDeviceUsage/);
  assert.match(server, /device-usage\.json/);
  assert.doesNotMatch(server, /recordUsageSnapshot/);
  assert.match(server, /30 \* 60/);
  assert.doesNotMatch(server, /url\.pathname === "\/api\/relay-stats"/);
  assert.match(server, /body\.deviceId/);
  assert.match(server, /targetDeviceId/);
  assert.match(server, /body\.force === true/);
  assert.match(server, /!force && outstanding\.length === 0/);
  assert.match(server, /deviceAuthRoot/);
  assert.match(server, /\/api\/device\/credentials/);
  assert.match(server, /deduplicatedCount/);
  assert.match(server, /availableAt/);
  assert.match(server, /executionResult/);
  assert.match(server, /90_000/);
  assert.match(server, /customName/);
  assert.match(server, /x-codex-active-account/);
  assert.match(server, /codexAuthState/);
  assert.match(server, /await refreshAccount\(activateMatch\[1\]\)/);
  assert.match(server, /request\.method === "PATCH"/);
  assert.match(server, /isOnline/);
  assert.doesNotMatch(server, /refreshTiboMonitor|codex-resets\.com|\/api\/tibo-monitor/);
  assert.doesNotMatch(server, /thread\/start|turn\/start|\/api\/forward/);
  assert.match(css, /grid-template-columns:\s*repeat\(2/);
  assert.match(css, /@keyframes progress-grow/);
  assert.match(css, /@keyframes progress-shine/);
  assert.match(css, /\.dual-quota-block/);
  assert.match(css, /\.quota-token-tooltip/);
  assert.match(css, /@keyframes metric-flash/);
  assert.match(css, /\.daily-usage-panel/);
  assert.match(css, /\.plus-equivalent/);
  assert.match(css, /\.plus-metric/);
  assert.match(css, /\.remaining-plus-summary/);
  assert.match(css, /\.plus-battery/);
  assert.match(css, /@keyframes battery-shine/);
  assert.match(css, /\.daily-tooltip-plus/);
  assert.match(css, /@keyframes daily-bar-shine/);
  assert.match(css, /\.daily-column:hover \.daily-tooltip/);
  assert.match(css, /\.floating-directory/);
  assert.match(css, /@keyframes section-rise/);
  assert.match(css, /\.usage-insights/);
  assert.match(css, /\.history-pagination/);
});

test("deployment and desktop switchers preserve Codex task storage", async () => {
  const compose = await readFile(new URL("../compose.yaml", import.meta.url), "utf8");
  const dockerfile = await readFile(new URL("../Dockerfile", import.meta.url), "utf8");
  const dockerEntrypoint = await readFile(new URL("../local/docker-entrypoint.sh", import.meta.url), "utf8");
  const macSwitcher = await readFile(new URL("../mac/apply-switch.sh", import.meta.url), "utf8");
  const windowsSwitcher = await readFile(new URL("../windows/apply-switch.ps1", import.meta.url), "utf8");
  const macAgent = await readFile(new URL("../mac/mac-agent.sh", import.meta.url), "utf8");
  const windowsAgent = await readFile(new URL("../windows/windows-agent.ps1", import.meta.url), "utf8");
  assert.match(compose, /ACCOUNT_MANAGER_DATA_DIR: \/data/);
  assert.match(compose, /USAGE_REFRESH_INTERVAL_MS: 300000/);
  assert.match(dockerfile, /CMD \["node", "--experimental-strip-types", "local\/run\.ts", "start"\]/);
  assert.match(dockerfile, /ENTRYPOINT \["\/app\/local\/docker-entrypoint\.sh"\]/);
  assert.match(dockerfile, /ca-certificates gosu/);
  assert.match(dockerEntrypoint, /chown -R node:node \/data/);
  assert.match(dockerEntrypoint, /exec gosu node/);
  assert.match(macSwitcher, /CODEX_DIR="\$HOME\/\.codex"/);
  assert.match(macSwitcher, /TARGET_AUTH="\$CODEX_DIR\/auth\.json"/);
  assert.match(windowsSwitcher, /Join-Path \$env:USERPROFILE "\.codex"/);
  assert.match(windowsSwitcher, /Join-Path \$CodexDir "auth\.json"/);
  assert.match(macSwitcher, /ACCOUNT_CACHE_DIR/);
  assert.match(macSwitcher, /SERVER_ACCOUNT_ID/);
  assert.match(windowsSwitcher, /AccountCacheDir/);
  assert.match(windowsSwitcher, /ServerAccountId/);
  assert.match(macAgent, /SWITCHER_VERSION="1\.8\.0"/);
  assert.match(windowsAgent, /\$SwitcherVersion = "1\.8\.0"/);
  assert.match(macSwitcher, /find_newest_auth/);
  assert.match(macSwitcher, /last_refresh/);
  assert.match(macSwitcher, /printf '%s\\n' "\$TARGET_AUTH"/);
  assert.match(windowsSwitcher, /Find-NewestAuth/);
  assert.match(windowsSwitcher, /last_refresh/);
  assert.match(windowsSwitcher, /@\(\$TargetAuth, \(Get-CachePath \$ExpectedAccountId\)\)/);
  assert.match(macAgent, /command_was_processed/);
  assert.match(macAgent, /mark_command_processed/);
  assert.match(windowsAgent, /Get-ProcessedCommandPath/);
  assert.match(windowsAgent, /Set-CommandProcessed/);
  assert.match(macAgent, /\/api\/device\/credentials/);
  assert.match(windowsAgent, /\/api\/device\/credentials/);
  assert.match(macAgent, /X-Codex-Active-Account/);
  assert.match(windowsAgent, /X-Codex-Active-Account/);
  assert.doesNotMatch(`${macSwitcher}\n${windowsSwitcher}`, /state_5\.sqlite|sessions|rollout/);
});

test("Windows pairing and installer are included", async () => {
  const dashboard = await readFile(new URL("../app/dashboard.tsx", import.meta.url), "utf8");
  const server = await readFile(new URL("../local/server.ts", import.meta.url), "utf8");
  const installer = await readFile(new URL("../windows/install-windows.ps1", import.meta.url), "utf8");
  const agent = await readFile(new URL("../windows/windows-agent.ps1", import.meta.url), "utf8");
  const switcher = await readFile(new URL("../windows/apply-switch.ps1", import.meta.url), "utf8");
  const uninstaller = await readFile(new URL("../windows/uninstall-windows.ps1", import.meta.url), "utf8");
  assert.match(dashboard, /连接 Windows/);
  assert.match(dashboard, /修复连接/);
  assert.match(dashboard, /更新切换器/);
  assert.match(dashboard, /不会创建重复设备/);
  assert.match(server, /install-windows\.ps1/);
  assert.match(server, /\/repair/);
  assert.match(server, /body\.platform === "windows"/);
  assert.match(installer, /CurrentVersion\\Run/);
  assert.match(installer, /Register-ScheduledTask/);
  assert.match(installer, /start-agent\.vbs/);
  assert.match(installer, /\[switch\]\$Repair/);
  assert.match(installer, /GPTAccountSwitcherInstaller/);
  assert.match(installer, /api\/device\/ping/);
  assert.match(installer, /installationId/);
  assert.equal([...`${installer}${agent}${switcher}${uninstaller}`].every((character) => character.codePointAt(0) <= 127), true);
  assert.match(agent, /api\/device\/commands\/next/);
  assert.match(agent, /agent\.log/);
  assert.match(agent, /TimeoutSec 20/);
  assert.match(agent, /WindowsPowerShell\\v1\.0\\powershell\.exe/);
  assert.match(agent, /\$applyStatus/);
  assert.match(agent, /Sync-CurrentCredentials/);
  assert.match(switcher, /RollbackAuth/);
  assert.match(switcher, /Start-ChatGPTApp/);
  assert.match(switcher, /Wait-ChatGPTWindow/);
  assert.match(switcher, /\*ChatGPT\*\.lnk/);
  assert.match(switcher, /Stop-Process -Id \$_\.Id -Force -ErrorAction SilentlyContinue/);
  assert.doesNotMatch(switcher, /taskkill\.exe/);
  assert.match(installer, /TimeoutSec 30/);
  assert.match(server, /registeredResponse/);
  assert.match(server, /normalizeInstallationId/);
  assert.match(server, /Downloading the Windows switcher/);
  assert.match(server, /Invoke-WebRequest -UseBasicParsing -TimeoutSec 30/);
});
